{
 "title": "Kubernetes",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "label": "Nodes",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$Namespace\", container=~\"$Container\"},pod)"
    }
   },
   {
    "name": "Container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$Namespace\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resources Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Namespace Resource Statistics",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_pod_info{}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{}) by(namespace)"
    },
    {
     "expr": "count(kube_configmap_info{}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{}) by(namespace)",
     "legendFormat": "secret"
    }
   ]
  },
  {
   "title": "CPU Cores Information",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"$Node\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{node=~\"$Node\"}[2m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"$Node\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"$Node\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU Ratio",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{node=~\"$Node\"}[2m])) \r\n/ \r\nsum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"$Node\"})",
     "legendFormat": "Utilization Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"$Node\"}) \r\n/ \r\nsum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"$Node\"})",
     "legendFormat": "Request Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"$Node\"}) \r\n/ \r\nsum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"$Node\"})",
     "legendFormat": "Limit Rate"
    }
   ]
  },
  {
   "title": "Memory Information",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"$Node\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{node=~\"$Node\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"$Node\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"$Node\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Memory Ratio",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{node=~\"$Node\"}) \r\n/ \r\nsum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"$Node\"})",
     "legendFormat": "Utilization Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"$Node\"}) \r\n/ \r\nsum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"$Node\"})",
     "legendFormat": "Request Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"$Node\"}) \r\n/\r\nsum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"$Node\"})",
     "legendFormat": "Limit Rate"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"$Node\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{node=~\"$Node\", namespace=~\"$Namespace\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "CPU Used Cores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"$Node\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{node=~\"$Node\",namespace=~\"$Namespace\"}[2m]))",
     "legendFormat": "Usage"
    }
   ]
  }
 ]
}