{
 "title": "OpenTelemetry Demo",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Graph",
   "type": "nodeGraph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "limit": 20, "metricsQueryType": "range", "serviceMapQuery": "{}", "tableType": "traces" }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 } },
  { "title": "Ad", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Ad CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\r\nsum by (pod) (\r\n  rate(container_cpu_usage_seconds_total{\r\n    pod=~\"ad-.*\",\r\n  }[5m])\r\n)\r\n/\r\nclamp_min(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      pod=~\"ad-.*\",\r\n      resource=\"cpu\",\r\n    }\r\n  ),\r\n  0.001\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ad CPU Problem Pattern",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"ad\", job != \"loki.source.kubernetes.pods_logs\"} |~ \"High CPU-Load problempattern enabled\""
    }
   ]
  },
  {
   "title": "Ad Failure",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name = \"ad\", job != \"loki.source.kubernetes.pods_logs\"} |~ \"GetAds Failed with status Status\""
    }
   ]
  },
  {
   "title": "Ad Manual Garbage Collector",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"ad\", job != \"loki.source.kubernetes.pods_logs\"} \r\n|~ \"Feature Flag adManualGc enabled|Triggering a manual garbage collection|The artificially triggered GCs took\""
    }
   ]
  },
  { "title": "Cart", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Cart EmptyCart Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\r\nsum by (service_name, span_name) (\r\n  rate(traces_span_metrics_calls_total{\r\n    service_name=\"cart\",\r\n    span_name=\"POST /oteldemo.CartService/EmptyCart\",\r\n    status_code=\"STATUS_CODE_ERROR\"\r\n  }[5m])\r\n)\r\n/\r\nclamp_min(\r\n  sum by (service_name, span_name) (\r\n    rate(traces_span_metrics_calls_total{\r\n      service_name=\"cart\",\r\n      span_name=\"POST /oteldemo.CartService/EmptyCart\"\r\n    }[5m])\r\n  ),\r\n  0.000001\r\n)",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Cart Failure",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name = \"cart\"} |~ \"Can't access cart storage\""
    }
   ]
  },
  { "title": "Recommendation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Recommendation Status 500",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\r\nsum by (target) (\r\n  rate(app_frontend_requests_total{\r\n    target=\"/api/recommendations\",\r\n    status=\"500\"\r\n  }[5m])\r\n)\r\n/\r\nclamp_min(\r\n  sum by (target) (\r\n    rate(app_frontend_requests_total{\r\n      target=\"/api/recommendations\"\r\n    }[5m])\r\n  ),\r\n  0.000001\r\n)",
     "legendFormat": "500 {{target}}"
    }
   ]
  },
  {
   "title": "Recommendation Failure",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"recommendation\"} |~ \"Exception calling application\""
    }
   ]
  }
 ]
}