{
 "title": "Traefik",
 "description": "Official dashboard for Traefik on Kubernetes",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Traefik Instances",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(traefik_config_reloads_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Code",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{protocol=\"http\"}[2m])) by (method, code)",
     "legendFormat": "{{method}} - {{code}}"
    }
   ]
  },
  {
   "title": "Top Slow Services",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        traefik_service_request_duration_seconds_sum{protocol=\"http\"} / \n          traefik_service_request_duration_seconds_count{protocol=\"http\"},\n        \"service\", \"$1\", \"service\", \"([^@]+)@.*\")\n)\n\n",
     "legendFormat": "{{method}} - {{code}}"
    }
   ]
  },
  {
   "title": "Requests Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        sum by (service,method) \n          (rate(traefik_service_requests_bytes_total{protocol=\"http\"}[2m])) > 0,\n        \"service\", \"$1\", \"service\", \"([^@]+)@.*\")\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Responses Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        sum by (service,method) \n          (rate(traefik_service_responses_bytes_total{protocol=\"http\"}[2m])) > 0,\n        \"service\", \"$1\", \"service\", \"([^@]+)@.*\")\n)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}